spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///springdb
    username: root
    password: 123
  thymeleaf:
    cache: false

    
server:
  servlet:
    context-path: /myweb
    